=== CompNet/Nerwip/res/schemas/categorymaps.xsd
<?xml version="1.0" encoding="utf-8"?>

<!-- 
	Nerwip - Named Entity Extraction in Wikipedia Pages
	Copyright 2011-17 Vincent Labatut et al.
	
	This file is part of Nerwip - Named Entity Extraction in Wikipedia Pages.
	
	Nerwip - Named Entity Extraction in Wikipedia Pages is free software: you can 
	redistribute it and/or modify it under the terms of the GNU General Public License 
	as published by the Free Software Foundation, either version 2 of the License, or
	(at your option) any later version.
	 
	Nerwip - Named Entity Extraction in Wikipedia Pages is distributed in the hope 
	that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty 
	of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public 
	License for more details.
	
	You should have received a copy of the GNU General Public License
	along with Nerwip - Named Entity Extraction in Wikipedia Pages.  
	If not, see <http://www.gnu.org/licenses/>.
 -->
 
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<xsd:include schemaLocation="_categories.xsd"/>

	<xsd:complexType name="tAcceptMap">
		<xsd:sequence>
			<xsd:element name="key" type="xsd:string" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
		<xsd:attribute name="name" type="tCategory" use="required" />
	</xsd:complexType>

	<xsd:complexType name="tAccept">
		<xsd:sequence>
			<xsd:element name="category" type="tAcceptMap" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="tRejectMap">
		<xsd:sequence>
			<xsd:element name="key" type="xsd:string" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="tReject">
		<xsd:sequence>
			<xsd:element name="startsWith" type="tRejectMap" minOccurs="0" maxOccurs="unbounded" />
			<xsd:element name="endsWith" type="tRejectMap" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="tCategoryMap">
		<xsd:sequence>
			<xsd:element name="accept" type="tAccept" minOccurs="0" />
			<xsd:element name="reject" type="tReject" minOccurs="0" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:element name="categoryMap" type="tCategoryMap" />

</xsd:schema>

=== CompNet/Nerwip/res/retrieval/catmap.content.xml
<?xml version="1.0" encoding="utf-8"?>
<categoryMap
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:noNamespaceSchemaLocation="../schemas/categorymaps.xsd">
<!-- 
	Nerwip - Named Entity Extraction in Wikipedia Pages
	Copyright 2011-16 Vincent Labatut et al.
	
	This file is part of Nerwip - Named Entity Extraction in Wikipedia Pages.
	
	Nerwip - Named Entity Extraction in Wikipedia Pages is free software: you can 
	redistribute it and/or modify it under the terms of the GNU General Public License 
	as published by the Free Software Foundation, either version 2 of the License, or
	(at your option) any later version.
	 
	Nerwip - Named Entity Extraction in Wikipedia Pages is distributed in the hope 
	that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty 
	of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public 
	License for more details.
	
	You should have received a copy of the GNU General Public License
	along with Nerwip - Named Entity Extraction in Wikipedia Pages.  
	If not, see <http://www.gnu.org/licenses/>.
 -->

	<accept>
		<category name="ACADEMIA">
			<key>academic</key>
			<key>astronomer</key>
			<key>author</key>
			<key>biologist</key>
			<key>biochemist</key>
			<key>botanist</key>
			<key>chemist</key>
			<key>economist</key>
			<key>educator</key>
			<key>engineer</key>
			<key>essayist</key>
			<key>geographer</key>
			<key>geologist</key>
			<key>herpetologist</key>
			<key>historian</key>
			<key>intellectual</key>
			<key>lecturer</key>
			<key>mathematician</key>
			<key>microbiologist</key>
			<key>nobel</key>
			<key>neuroscientist</key>
			<key>paleontologist</key>
			<key>philosopher</key>
			<key>physicist</key>
			<key>professor</key>
			<key>scholar</key>
			<key>science</key>
			<key>scientist</key>
			<key>statistician</key>
			<key>teacher</key>
		</category>
		
		<category name="ARCHITECTURE">
			<key>architect</key>
		</category>
		
		<category name="ART">
			<key>accordion</key>
			<key>actor</key>
			<key>actress</key>
			<key>alto</key>
			<key>art</key>
			<key>artisan</key>
			<key>artist</key>
			<key>bagpipe</key>
			<key>baritone</key>
			<key>bass</key>
			<key>bassoon</key>
			<key>cartoonist</key>
			<key>clarinet</key>
			<key>choreographer</key>
			<key>colorist</key>
			<key>contralto</key>
			<key>countertenor</key>
			<key>curator</key>
			<key>dancer</key>
			<key>drum</key>
			<key>drummer</key>
			<key>dramaturg</key>
			<key>designer</key>
			<key>fashion</key>
			<key>flute</key>
			<key>flutist</key>
			<key>ghostwriter</key>
			<key>guitar</key>
			<key>harmonica</key>
			<key>harp</key>
			<key>harpist</key>
			<key>horn</key>
			<key>mandolin</key>
			<key>mezzosoprano</key>
			<key>mime</key>
			<key>model</key>
			<key>musician</key>
			<key>oboe</key>
			<key>organ</key>
			<key>painter</key>
			<key>photographer</key>
			<key>pianist</key>
			<key>piano</key>
			<key>pipe</key>
			<key>playwright</key>
			<key>poet</key>
			<key>poetress</key>
			<key>sax</key>
			<key>saxophone</key>
			<key>scenographer</key>
			<key>screenwriter</key>
			<key>sculptor</key>
			<key>singer</key>
			<key>soprano</key>
			<key>stylist</key>
			<key>tenor</key>
			<key>trombone</key>
			<key>trumpet</key>
			<key>tuba</key>
			<key>usher</key>
			<key>viola</key>
			<key>violin</key>
			<key>vocalist</key>
		<key>writer</key>
		</category>
		
		<category name="BUSINESS">
			<key>businessman</key>
			<key>entrepreneur</key>
			<key>industrialist</key>
			<key>inventor</key>
			<key>manager</key>
			<key>marketer</key>
			<key>producer</key>
		</category>
		
		<category name="LAW">
			<key>attorney</key>
			<key>barrister</key>
			<key>judge</key>
			<key>jurist</key>
			<key>law</key>
			<key>lawyer</key>
		</category>
		
		<category name="MEDIA">
			<key>blogger</key>
			<key>broadcaster</key>
			<key>editor</key>
			<key>journalist</key>
			<key>publicist</key>
			<key>publisher</key>
			<key>presenter</key>
			<key>reporter</key>
			<key>television</key>
			<key>tv</key>
		</category>
		
		<category name="MEDICINE">
			<key>anesthesiologist</key>
			<key>cardiologist</key>
			<key>intensivist</key>
			<key>neonatologist</key>
			<key>endocrinologist</key>
			<key>geriatrician</key>
			<key>gastroenterologist</key>
			<key>hematologist</key>
			<key>internist</key>
			<key>nephrologist</key>
			<key>neurologist</key>
			<key>neurosurgeon</key>
			<key>nurse</key>
			<key>nursemaid</key>
			<key>obstetrician</key>
			<key>oncologist</key>
			<key>ophthamologist</key>
			<key>otolaryngologist</key>
			<key>pediatrician</key>
			<key>phlebotomist</key>
			<key>physician</key>
			<key>psychiatrist</key>
			<key>psychologist</key>
			<key>pulmonologist</key>
			<key>radiologist</key>
			<key>sonographer</key>
			<key>surgeon</key>
			<key>therapist</key>
			<key>urologist</key>
		</category>
		
		<category name="MILITARY">
			<key>admiral</key>
			<key>army</key>
			<key>astronaut</key>
			<key>brigadier</key>
			<key>commander</key>
			<key>corporal</key>
			<key>cosmonaut</key>
			<key>colonel</key>
			<key>cosmonaut</key>
			<key>ensign</key>
			<key>general</key>
			<key>lieutenant</key>
			<key>marshal</key>
<!-- 		<key>major</key>  too many false positives -->
			<key>military</key>
			<key>navy</key>
			<key>sergeant</key>
			<key>soldier</key>
			<key>spationaut</key>
		</category>
		
		<category name="POLITICS">
			<key>activist</key>
			<key>ambassador</key>
			<key>communist</key>
			<key>congressman</key>
			<key>diplomat</key>
			<key>governor</key>
			<key>leader</key>
			<key>mayor</key>
			<key>minister</key>
			<key>ministry</key>
			<key>nationalist</key>
			<key>parliament</key>
			<key>party</key>
			<key>political</key>
			<key>politician</key>
			<key>president</key>
			<key>rebel</key>
			<key>senate</key>
			<key>senator</key>
			<key>socialist</key>
			<key>statesman</key>
			<key>unionist</key>
		</category>
		
		<category name="RELIGION">
			<key>archbishop</key>
			<key>ayatollah</key>
			<key>bishop</key>
			<key>cardinal</key>
			<key>chaplain</key>
			<key>cleric</key>
			<key>deacon</key>
			<key>dervish</key>
			<key>hafiz</key>
			<key>imam</key>
			<key>missionary</key>
			<key>marabout</key>
			<key>mohel</key>
			<key>monk</key>
			<key>mullah</key>
			<key>patriarch</key>
			<key>pastor</key>
			<key>pope</key>
			<key>prelate</key>
			<key>priest</key>
			<key>rabbi</key>
			<key>rebbe</key>
			<key>religious</key>
			<key>reverend</key>
			<key>shaikh</key>
			<key>ulama</key>
			<key>vicar</key>
		</category>
		
		<category name="SPORT">
			<key>aikido</key>
			<key>archer</key>
			<key>archery</key>
			<key>athlete</key>
			<key>badminton</key>
			<key>baseball</key>
			<key>basketball</key>
			<key>bowling</key>
			<key>boxing</key>
			<key>boxer</key>
			<key>canoe</key>
			<key>canoer</key>
			<key>champion</key>
			<key>chess</key>
			<key>climbing</key>
			<key>climber</key>
			<key>coach</key>
			<key>cricket</key>
			<key>cyclist</key>
			<key>equitation</key>
			<key>fencing</key>
			<key>fencer</key>
			<key>football</key>
			<key>footballer</key>
			<key>golf</key>
			<key>golfer</key>
			<key>gridiron</key>
			<key>gymnast</key>
			<key>gymnastics</key>
			<key>handball</key>
			<key>hockey</key>
			<key>judo</key>
			<key>judoka</key>
			<key>jump</key>
			<key>jumper</key>
			<key>karate</key>
			<key>karateka</key>
			<key>kayak</key>
			<key>kayaking</key>
			<key>olympic</key>
			<key>olympics</key>
			<key>player</key>
			<key>polo</key>
			<key>racer</key>
			<key>racing</key>
			<key>rowing</key>
			<key>rower</key>
			<key>rugby</key>
			<key>running</key>
			<key>runner</key>
			<key>sailing</key>
			<key>sailer</key>
			<key>skateboard</key>
			<key>skateboarder</key>
			<key>ski</key>
			<key>skier</key>
			<key>skipper</key>
			<key>snooker</key>
			<key>snowboard</key>
			<key>snowboarder</key>
			<key>sport</key>
			<key>sports</key>
			<key>sumo</key>
			<key>surf</key>
			<key>surfer</key>
			<key>swim</key>
			<key>swimmer</key>
			<key>tennis</key>
			<key>voleyball</key>
			<key>weightlifting</key>
			<key>weightlifter</key>
			<key>wrestling</key>
			<key>wrestler</key>
		</category>
	</accept>

</categoryMap>

=== CompNet/Nerwip/res/retrieval/catmap.fb.xml
<?xml version="1.0" encoding="utf-8"?>
<categoryMap
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:noNamespaceSchemaLocation="../schemas/categorymaps.xsd">
<!-- 
	Nerwip - Named Entity Extraction in Wikipedia Pages
	Copyright 2011-17 Vincent Labatut et al.
	
	This file is part of Nerwip - Named Entity Extraction in Wikipedia Pages.
	
	Nerwip - Named Entity Extraction in Wikipedia Pages is free software: you can 
	redistribute it and/or modify it under the terms of the GNU General Public License 
	as published by the Free Software Foundation, either version 2 of the License, or
	(at your option) any later version.
	 
	Nerwip - Named Entity Extraction in Wikipedia Pages is distributed in the hope 
	that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty 
	of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public 
	License for more details.
	
	You should have received a copy of the GNU General Public License
	along with Nerwip - Named Entity Extraction in Wikipedia Pages.  
	If not, see <http://www.gnu.org/licenses/>.
 -->

	<accept>
		<category name="ACADEMIA">
			<key>/astronomy</key>
			<key>/biology</key>
			<key>/chemistry</key>
			<key>/computer</key>
			<key>/conferences</key>
			<key>/education</key>
			<key>/engineering</key>
			<key>/geography</key>
			<key>/geology</key>
			<key>/library</key>
			<key>/measurement_unit</key>
			<key>/physics</key>
			<key>/spaceflight</key>
		</category>
		
		<category name="ARCHITECTURE">
			<key>/architecture</key>
		</category>
		
		<category name="ART">
			<key>/book</key>
			<key>/comic_books</key>
			<key>/exhibitions</key>
			<key>/fashion</key>
			<key>/fictional_universe</key>
			<key>/film</key>
			<key>/music</key>
			<key>/opera</key>
			<key>/theater</key>
			<key>/visual_art</key>
		</category>
		
		<category name="BUSINESS">
			<key>/amusement_parks</key>
			<key>/automotive</key>
			<key>/aviation</key>
			<key>/bicycles</key>
			<key>/boats</key>
			<key>/business</key>
			<key>/cvg</key>
			<key>/dataworld</key>
			<key>/food</key>
			<key>/rail</key>
			<key>/transportation</key>
			<key>/travel</key>
		</category>
		
		<category name="LAW">
			<key>/law</key>
		</category>
		
		<category name="MEDIA">
			<key>/broadcast</key>
			<key>/celebrities</key>
			<key>/meteorology</key>
			<key>/periodicals</key>
			<key>/radio</key>
			<key>/royalty</key>
			<key>/tv</key>
		</category>
		
		<category name="MEDICINE">
			<key>/medicine</key>
		</category>
		
		<category name="MILITARY">
			<key>/military</key>
		</category>
		
		<category name="POLITICS">
			<key>/government</key>
		</category>
		
		<category name="RELIGION">
			<key>/religion</key>
		</category>
		
		<category name="SPORT">
			<key>/american_football</key>
			<key>/baseball</key>
			<key>/basketball</key>
			<key>/boxing</key>
			<key>/chess</key>
			<key>/cricket</key>
			<key>/ice_hockey</key>
			<key>/martial_arts</key>
			<key>/olympics</key>
			<key>/skiing</key>
			<key>/soccer</key>
			<key>/sports</key>
			<key>/tennis</key>
		</category>
	</accept>
	
	<reject>
		<startsWith>
			<key>/award</key>
			<key>/base</key>
			<key>/common</key>
			<key>/digicams</key>
			<key>/event</key>
			<key>/freebase</key>
			<key>/games</key>
			<key>/interests</key>
			<key>/influence</key>
			<key>/internet</key>
			<key>/language</key>
			<key>/location</key>
			<key>/media_common</key>
			<key>/m</key>
			<key>/organization</key>
			<key>/people</key>
			<key>/projects</key>
			<key>/protected_sites</key>
			<key>/symbols</key>
			<key>/time</key>
			<key>/type</key>
			<key>/user</key>
			<key>/zoos</key>
		</startsWith>
		
		<endsWith>
			<key>/kwtopic</key>
			<key>/topic</key>
		</endsWith>
	</reject>

</categoryMap>
